### ISSUE TITLE
QrSegment() constructor documents a constraint that isn't checked

### ISSUE THREAD

**Issue by paulhoadley** [logicsquad/qr4j#3]
Specifically:

```
* The character count ({@code numCh}) must agree with the mode
* and the bit buffer length, but the constraint isn't checked.
```

Perhaps we could check this.

**Comment by nayuki** [comment]
`numCh` is the literal number that gets put into the segment's field when it is written to the QR Code modules, and it reflects the number of high-level characters that are being represented. `bitLen` is the actual number of bits in the bit buffer, which also gets written to the QR Code modules.

If I recall correctly, the constraint goes something like this:

    if (md == Mode.NUMERIC      && bitLen != numCh * 10 / 3) throw new IllegalArgumentException();
    if (md == Mode.ALPHANUMERIC && bitLen != numCh * 11 / 2) throw new IllegalArgumentException();
    ...

See the QR Code specification starting at PDF page 33 (numbered page 25): https://web.archive.org/web/20140630004133/https://www.codeplex.com/Download?ProjectName=qrcodenet&DownloadId=321409
